name: Debug E2E Test

on: [push]

jobs:
  debug-test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.1-jammy
      options: --shm-size=2gb

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Debug page load
        run: |
          cat << EOF > debug-test.js
          const { chromium } = require('@playwright/test');
          
          (async () => {
            const browser = await chromium.launch({
              args: ['--no-sandbox', '--disable-dev-shm-usage']
            });
            const page = await browser.newPage();
          
            console.log('Starting navigation...');
            await page.goto('https://epicbet.com/sports/');
            console.log('Page loaded');
          
            await page.waitForLoadState('networkidle');
            console.log('Network idle');
          
            const html = await page.content();
            console.log('Page content length:', html.length);
          
            await browser.close();
          })();
          EOF
          node debug-test.js

      - name: Run actual test
        run: npx playwright test
        env:
          DEBUG: pw:api