name: E2E Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.1-jammy
      options:
        --ipc=host # Add this for better iframe handling

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install chromium --with-deps

      # Add this new step to handle cookies and site initialization
      - name: Initialize site state
        run: |
          cat << EOF > init.js
          const { chromium } = require('@playwright/test');
          (async () => {
            const browser = await chromium.launch({
              args: ['--no-sandbox', '--disable-dev-shm-usage']
            });
            const context = await browser.newContext({
              ignoreHTTPSErrors: true,
              bypassCSP: true
            });
            const page = await context.newPage();
            await page.goto('https://epicbet.com/en/sports/', {
              waitUntil: 'networkidle',
              timeout: 60000
            });
            await browser.close();
          })();
          EOF
          node init.js

      - name: Run Playwright tests
        run: |
          npx playwright test --config=playwright.config.ts
        env:
          PLAYWRIGHT_LAUNCH_OPTIONS: >-
            {
              "args": [
                "--no-sandbox",
                "--disable-dev-shm-usage",
                "--disable-web-security",
                "--disable-features=IsolateOrigins,site-per-process"
              ]
            }
          DEBUG: pw:api

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/